version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - curl -fsSL https://rpm.nodesource.com/setup_22.x | bash -
      - yum install -y nodejs
      - node -v
      - npm ci
  build:
    commands:
      - npm prisma generate
      - npm build
artifacts:
  files:
    - '**/*'
